classdef aten__dropout_11 < nnet.layer.Layer & nnet.layer.Formattable
    %aten__dropout_11 Auto-generated custom layer
    % Auto-generated by MATLAB on 26-Oct-2022 11:08:23
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        
        
        dropout_3
        
        
        dropout_4
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = aten__dropout_11(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [dropout_input0_1, dropout_input0_1_rank] = predict(obj,dropout_input_1, dropout_input_1_rank)
            
            if ~contains(dims(dropout_input_1),'U')
                [dropout_input_1] = struct('value', dropout_input_1, 'rank', ndims(dropout_input_1));
            else
                [dropout_input_1] = struct('value', dropout_input_1, 'rank', int32(numel(dropout_input_1_rank)));
            end
            
            import traced_mnasnet1_0.ops.*;
            
            [dropout_3] = makeStructForConstant(single(obj.dropout_3), int32(0), "Typed");
            [dropout_4] = makeStructForConstant(int32(obj.dropout_4), int32(0), "Typed");
            [dropout_input0_1] = pyDropout(dropout_input_1, dropout_3, false);
            [dropout_input0_1_rank] = ones([1,dropout_input0_1.rank]);
            dropout_input0_1_rank = dlarray(dropout_input0_1_rank,'UU');
            dropout_input0_1 = dropout_input0_1.value ;
            
        end
        
        
        
        function [dropout_input0_1, dropout_input0_1_rank] = forward(obj,dropout_input_1, dropout_input_1_rank)
            
            if ~contains(dims(dropout_input_1),'U')
                [dropout_input_1] = struct('value', dropout_input_1, 'rank', ndims(dropout_input_1));
            else
                [dropout_input_1] = struct('value', dropout_input_1, 'rank', int32(numel(dropout_input_1_rank)));
            end
            
            import traced_mnasnet1_0.ops.*;
            
            [dropout_3] = makeStructForConstant(single(obj.dropout_3), int32(0), "Typed");
            [dropout_4] = makeStructForConstant(int32(obj.dropout_4), int32(0), "Typed");
            [dropout_input0_1] = pyDropout(dropout_input_1, dropout_3, true);
            [dropout_input0_1_rank] = ones([1,dropout_input0_1.rank]);
            dropout_input0_1_rank = dlarray(dropout_input0_1_rank,'UU');
            dropout_input0_1 = dropout_input0_1.value ;
            
        end
        
        
    end
end

